name: pull-request

on:
  - pull_request

jobs:
  pull-request:
    name: pull-request

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install packages
        run: dotnet restore

      - name: build
        run: dotnet build
        
      - name: pack
        run: dotnet pack