name: push

on:
  - push

jobs:
  push:
    name: push

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dotnet 2.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.0.x

      - name: install packages
        run: dotnet restore

      - name: build
        run: dotnet build
