name: publish
on:
  release:
    types: [published]
    branches:
      - master # Default release branch
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: install packages
        run: dotnet restore
          
      - name: build
        run: dotnet build
        
      - name: publish
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: Byndyusoft.DotNet.Web.ProjectTemplate.csproj
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true